apiVersion: v1
kind: Pod
metadata:
  name: nginx-client
  namespace: cilium-test
  labels:
    app: client
spec:
  containers:
  - name: client
    image: nginx:latest
    command: [ "sleep", "infinity" ] # Keeps the client Pod running for interaction
  nodeSelector:
    kubernetes.io/hostname: node-2 # Specify the worker node for the client

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-server
  namespace: cilium-test
  labels:
    app: server
spec:
  containers:
  - name: server
    image: nginx:latest
    ports:
    - containerPort: 80
  nodeSelector:
    kubernetes.io/hostname: node-2 # Specify the worker node for the server

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: cilium-test
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

